.

diff --git a/src/pgsql/bin/functions/close_partners_slots b/src/pgsql/bin/functions/close_partners_slots
--- a/src/pgsql/bin/functions/close_partners_slots
+++ b/src/pgsql/bin/functions/close_partners_slots
@@ -8,11 +8,11 @@ echo "$SLOTS"
 echo ">>> Closing slots which exist on master node"
 for SLOT in ${SLOTS[@]}; do
     echo ">>>>>> Closing slot $SLOT"
-    gosu postgres psql -U $POSTGRES_USER -tAc "SELECT pg_drop_replication_slot('$SLOT')" || echo ">>>>>>>>> Can't close the slot!"
+    gosu postgres psql -tAc "SELECT pg_drop_replication_slot('$SLOT')" || echo ">>>>>>>>> Can't close the slot!"
 done
 
 echo ">>> Closing slot which current master used on the node"
 MASTER_ID=`get_upstream_node_id`
 SLOT_NAME=$REPMGR_SLOT_NAME_PREFIX$MASTER_ID
 echo ">>>>>> Closing slot $SLOT_NAME"
-gosu postgres psql -U $POSTGRES_USER -tAc "SELECT pg_drop_replication_slot('$SLOT_NAME');" || echo ">>>>>>>>> Can't close the slot!"
+gosu postgres psql -tAc "SELECT pg_drop_replication_slot('$SLOT_NAME');" || echo ">>>>>>>>> Can't close the slot!"
